### ISSUE TITLE
Should item -power:>=1260 be -powerlimit:>=1260 

### ISSUE THREAD

**Issue by ASlowToad** [TMMania/TMManias-DIM-Filter-Gallery#3]
Thanks for the filter.

Should item -power: use some variation of powerlimit: or were you just making sure that items that are at max power for the season are not deleted?

**Comment by TMMania** [comment]
-power is correct. In the "Alternate Cases" section, I use (is:armor is:sunset), that line is 3rd from the bottom. For weapons, at the very top, I have a is:sunset in the multi-case section for weapons. So those two lines handle sunset items, that is for making sure you keep multiple copies of max power items for the season since is:maxpower only keeps 1 copy of each.

**Comment by TMMania** [comment]
I changed up the way it's written because -power:>=1310 makes no sense with the >, so I just set it to -power:=1310

**Comment by ASlowToad** [comment]
Initially I was reading it as 1210, missed that the value was max power for the season rather than max power that the item could be infused too.  To bad DIM's filters don't have a way to add comments to filters.  You would probably get fewer questions.  Thanks for the investigation you put in to determine what values to use as well as the time to test and debug.

**Comment by TMMania** [comment]
I just changed it from 1260 to 1310 for the new season. I'm also developing a system to include "comments" and you can preview that in the Build A Filter module.
